version: '3'

volumes: 
  dynamodb_data:

services:
  dynamodb:
    ports: 
     - "8000:8000"
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb
    volumes:
     - dynamodb_data:/home/ian/dynamodblocal/data/
